 #Your build pipeline references an undefined variable named ‘FirstName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘LastName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

parameters:
- name: SolutionName
  displayName: Select Soultion to Deploy
  type: string
  default: Base
  values:
  - Sol1
  - Sol2
  - Sol3
  - Base


steps:
- script: 'python app.py $(FirstName) $(LastName) > $(Build.BinariesDirectory)\out.txt'
  displayName: 'Command Line Script'

- script: |
   echo "${{ parameters.SolutionName }}"
   echo "Hello world"
  displayName: 'Command Line Script'

- script: |
   echo "3"
   echo "Hello world"
  displayName: 'Command Line Script'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)'
  
- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)\out.txt'

- powershell: |
   Write-Host "Solution Version" ${env:SOLUTIONVERSION}
   
   $version = ${env:SOLUTIONVERSION}
   $versionList = $version.split('.')
   
   $versionList[$versionList.length-1] = [int]::Parse($versionList[$versionList.length-1])+1
   
   $version = [string]::join(".",$versionList)
   
   Write-Host "Next Version: " $version
   
   Write-Host "Setting SolutionVersion to ($version)"
   Write-Host "##vso[task.setvariable variable=SolutionVersion;]$version"
   
   Write-Host "SolutionVersion: " $version
  displayName: 'Get Next Version: $(Solution)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**\.zip'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'